fmapp2: Declared required libs usage
* Solves:
 error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [qcom.fmradio]
	- optional libraries in build system: []
	                 vs. in the manifest: []
	- tags in the manifest (out/soong/.intermediates/vendor/qcom/opensource/fm-commonsys/fmapp2/FM2/android_common/manifest_fixer/AndroidManifest.xml):
		<uses-library android:name="qcom.fmradio" android:required="true"/>

* Test: Package successfully builds

Signed-off-by: Henrique Pereira <hlcpereira@pixelexperience.org>
Change-Id: I6d881f0eda1604fd1fcca7e879331c939940dbdf